[package]
name = "unknown91248/date"
description = "This is a util package that helps with managing days,months and dates in general."
authors = ["unknown91248"]
license = "MIT"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]